
import java.util.LinkedHashMap;
import java.util.Map;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
/**
 *
 * @author Jaime Carmona Loeches @date 29-abr-2012 @company Lument
 * (www.lument.es)
 */
@ManagedBean(name = "vincularDesvincularBean")
@SessionScoped
public class VincularDesvincularBean {

    public String entidad;
    public String usuarioVinculado;
    public String usuarioDesvinculado;
    //Generated by Map
    private Map<String, Object> entidadesValue;
    private Map<String, Object> usuariosVinculadosValue;
    private Map<String, Object> usuariosDesvinculadosValue;

    {
        entidadesValue = new LinkedHashMap<String, Object>();
        entidadesValue.put("Entidad 1", "1"); //label, value
        entidadesValue.put("Entidad 2", "2");
        entidadesValue.put("Entidad 3", "3");

        usuariosVinculadosValue = new LinkedHashMap<String, Object>();
        usuariosVinculadosValue.put("Usuario 1", "1"); //label, value
        usuariosVinculadosValue.put("Usuario 2", "2");
        usuariosVinculadosValue.put("Usuario 3", "3");

        usuariosDesvinculadosValue = new LinkedHashMap<String, Object>();
        usuariosDesvinculadosValue.put("Usuario 4", "4"); //label, value
        usuariosDesvinculadosValue.put("Usuario 5", "5");
        usuariosDesvinculadosValue.put("Usuario 6", "6");
    }

    public String getEntidad() {
        return entidad;
    }

    public void setEntidad(String entidad) {
        this.entidad = entidad;
    }

    public Map<String, Object> getEntidadesValue() {
        return entidadesValue;
    }

    public void setEntidadesValue(Map<String, Object> entidadesValue) {
        this.entidadesValue = entidadesValue;
    }

    public String getUsuarioDesvinculado() {
        return usuarioDesvinculado;
    }

    public void setUsuarioDesvinculado(String usuarioDesvinculado) {
        this.usuarioDesvinculado = usuarioDesvinculado;
    }

    public String getUsuarioVinculado() {
        return usuarioVinculado;
    }

    public void setUsuarioVinculado(String usuarioVinculado) {
        this.usuarioVinculado = usuarioVinculado;
    }

    public Map<String, Object> getUsuariosDesvinculadosValue() {
        return usuariosDesvinculadosValue;
    }

    public void setUsuariosDesvinculadosValue(Map<String, Object> usuariosDesvinculadosValue) {
        this.usuariosDesvinculadosValue = usuariosDesvinculadosValue;
    }

    public Map<String, Object> getUsuariosVinculadosValue() {
        return usuariosVinculadosValue;
    }

    public void setUsuariosVinculadosValue(Map<String, Object> usuariosVinculadosValue) {
        this.usuariosVinculadosValue = usuariosVinculadosValue;
    }
    
    
}
